### ISSUE TITLE
Awkward to package

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#288]
I'm looking at trying to package Dungeon Revealer for Arch Linux, and have run into an awkward spot. When `dungeon-revealer` is installed into `/usr/bin` (and owned by root), running it as a user gives:
```console
$ dungeon-revealer
pkg/prelude/bootstrap.js:1183
      throw error;
      ^

Error: EACCES: permission denied, mkdir '/usr/bin/data'
    at Object.fs.mkdirSync (fs.js:874:3)
    at Object.mkdirsSync (/snapshot/dungeon-revealer/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at Object.<anonymous> (/snapshot/dungeon-revealer/server/index.js:21:4)
    at Module._compile (pkg/prelude/bootstrap.js:1259:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1164:31)
```
It would be much better if the program used, say, the [XDG Standard Base Directories](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) for storage rather than trying to use paths relative to the location of the binary. Is that something you may consider supporting? Without it, it's pretty much impossible to package this program in a meaningful way.

**Comment by n1ru4l** [comment]
Any ideas for supporting this in a backwards-compatible way?

**Comment by jonhoo** [comment]
Hmm, you could check if a `data` directory exists, and if it does not, then use `$XDG_DATA_HOME/dungeon-revealer/`. If you wanted to be _really_ nice to Linux users, you could also factor out generated things into `$XDG_CACHE_HOME` and configs to `$XDG_CONFIG_HOME`, but that's _probably_ not worth it given the small data footprint this has anyway :)

**Comment by jonhoo** [comment]
@n1ru4l Thinking some more about this, you _may_ also want some logic in there that _moves_ `data` to `$XDG_DATA_HOME/dungeon-revealer/`, so that in the future you only have to use a single location.

**Comment by n1ru4l** [comment]
This package seems to be the correct lib for finding those folders cross platform https://github.com/sindresorhus/env-paths
