### ISSUE TITLE
v1.8.0 armv7 build is broken

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#551]
As mentioned by @hinjodragonfly the armv7 build is currently broken due to the sqlite3 binary being built with node:12, but the bundled version being 10.

**Original Error:**

```
./dungeon-revealer-linux-armv7
pkg/prelude/bootstrap.js:1183
throw error;
^

Error: The module '/home/pi/Desktop/revealer/node_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).
at Object.Module._extensions..node (internal/modules/cjs/loader.js:729:18)
at Module.load (internal/modules/cjs/loader.js:610:32)
at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
at Function.Module._load (internal/modules/cjs/loader.js:541:3)
at Module.require (internal/modules/cjs/loader.js:648:17)
at Module.require (pkg/prelude/bootstrap.js:1164:31)
at require (internal/modules/cjs/helpers.js:20:18)
at Object. (/snapshot/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
at Module._compile (pkg/prelude/bootstrap.js:1259:22)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
```

**Comment by maxb2** [comment]
In the workflow file we are using the `arm32v7/node:12` image but our pkg command is `pkg . --output ./bin/dungeon-revealer-linux-armv7 --targets node10-linux-armv7`.
