### ISSUE TITLE
Heroku one-click deployment fails

### ISSUE THREAD

**Issue by tirrip** [dungeon-revealer/dungeon-revealer#794]
Launching Heroku one-click deployment into a  Heroku pre-logged account causes application error upon opening app:

![image](https://user-images.githubusercontent.com/6159138/95815638-d23e7300-0d68-11eb-83f7-c6617fd2f387.png)

DM_PASSWORD  and PC_PASSWORD set before deployment to short alphanumeric only one word password for each.

**Comment by n1ru4l** [comment]
it would be nice to also include the error log 😅

**Comment by tirrip** [comment]
I replaced personal info with $$$$$$$$$ I'm not sure if this is all of it, but you should be able to duplicate it by simply runnning the Heroku one click deployment, it should crash for everyone?

2020-10-14T04:41:41.554903+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-10-14T04:41:41.563402+00:00 app[web.1]: 
2020-10-14T04:41:41.563707+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-10-14T04:41:41.563903+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-10-14T04_41_41_556Z-debug.log
2020-10-14T04:41:41.642649+00:00 heroku[web.1]: Process exited with status 1
2020-10-14T04:41:41.681792+00:00 heroku[web.1]: State changed from starting to crashed
2020-10-14T07:40:54.973700+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=$$$$$$$$$$$$$$$.herokuapp.com request_id=04e4edf2-927f-4455-b324-601f0179f35b fwd="$$$.$$$.$$$.$$$" dyno= connect= service= status=503 bytes= protocol=https
2020-10-14T07:40:55.272963+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=$$$$$$$$$$$$$$$.herokuapp.com request_id=3e25bc3c-4749-4216-8e21-4da4e24b842b fwd="$$$.$$$.$$$.$$$" dyno= connect= service= status=503 bytes= protocol=https
2020-10-14T07:41:41.412598+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=$$$$$$$$$$$$$$$.herokuapp.com request_id=1a2bff0f-73a2-4007-a48f-d3dec5d6a9e7 fwd="$$$.$$$.$$$.$$$" dyno= connect= service= status=503 bytes= protocol=https
2020-10-14T07:41:41.720345+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=$$$$$$$$$$$$$$$.herokuapp.com request_id=382ddb1a-37af-4b89-8d8b-3297852000bf fwd="$$$.$$$.$$$.$$$" dyno= connect= service= status=503 bytes= protocol=https
2020-10-14T07:42:19.056644+00:00 app[api]: Starting process with command `heroku logs --tail` by user $$$$$$$$$$$$$$$
2020-10-14T07:42:24.344615+00:00 heroku[run.5542]: State changed from starting to up
2020-10-14T07:42:24.561278+00:00 heroku[run.5542]: Awaiting client
2020-10-14T07:42:24.578682+00:00 heroku[run.5542]: Starting process with command `heroku logs --tail`
2020-10-14T07:42:29.356567+00:00 heroku[run.5542]: Process exited with status 127
2020-10-14T07:42:29.391650+00:00 heroku[run.5542]: State changed from up to complete
2020-10-14T07:42:54.223628+00:00 app[api]: Starting process with command `logs --tail` by user $$$$$$$$$$$$$$$
2020-10-14T07:43:00.676243+00:00 heroku[run.4253]: State changed from starting to up
2020-10-14T07:43:01.466011+00:00 heroku[run.4253]: Awaiting client
2020-10-14T07:43:01.496336+00:00 heroku[run.4253]: Starting process with command `logs --tail`
2020-10-14T07:43:05.838527+00:00 heroku[run.4253]: Process exited with status 127
2020-10-14T07:43:05.871242+00:00 heroku[run.4253]: State changed from up to complete

**Comment by tirrip** [comment]
after experimenting a bit, every time I run the Heroku app, it does this particular error:

 ($$$$$ where my personal info is)

2020-10-14T07:56:02.176285+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=$$$$$$$$$.herokuapp.com request_id=084a444f-818b-400d-808d-646082c088d9 fwd="138.25.91.189" dyno= connect= service= status=503 bytes= protocol=https
2020-10-14T07:56:02.443161+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=$$$$$$$$$.herokuapp.com request_id=17b124a0-0c8a-4967-a643-ab19f934eb2e fwd="138.25.91.189" dyno= connect= service= status=503 bytes= protocol=https

**Comment by maxb2** [comment]
Here is the full crash log:

```
 > dungeon-revealer@1.10.3 start /app
 > node ./bin/dungeon-revealer
 
 internal/modules/cjs/loader.js:834
   throw err;
   ^
 
 Error: Cannot find module 'socket.io-client/package.json'
 Require stack:
 - /app/node_modules/socket.io/lib/index.js
 - /app/server-build/server.js
 - /app/server-build/index.js
 - /app/bin/dungeon-revealer
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
     at Module.require (internal/modules/cjs/loader.js:903:19)
     at require (internal/modules/cjs/helpers.js:74:18)
     at Object.<anonymous> (/app/node_modules/socket.io/lib/index.js:12:21)
     at Module._compile (internal/modules/cjs/loader.js:1015:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
     at Module.load (internal/modules/cjs/loader.js:879:32)
     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
     at Module.require (internal/modules/cjs/loader.js:903:19) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/app/node_modules/socket.io/lib/index.js',
     '/app/server-build/server.js',
     '/app/server-build/index.js',
     '/app/bin/dungeon-revealer'
   ]
 }
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! dungeon-revealer@1.10.3 start: `node ./bin/dungeon-revealer`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the dungeon-revealer@1.10.3 start script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /app/.npm/_logs/2020-10-14T14_13_42_886Z-debug.log
```

**Comment by n1ru4l** [comment]
Is this cause by https://github.com/dungeon-revealer/dungeon-revealer/pull/770 ?

**Comment by maxb2** [comment]
I'll try a bisection on my fork.

**Comment by maxb2** [comment]
> Is this cause by #770 ?

The bug was introduced by this. The Heroku deployment is working up to 6e76df5.

**Comment by n1ru4l** [comment]
Can you please try https://github.com/dungeon-revealer/dungeon-revealer/pull/800

**Comment by maxb2** [comment]
#800 works!

**Comment by n1ru4l** [comment]
@tirrip Let us know if there are still issues. I am going to close this for now.

**Comment by tirrip** [comment]
work fine, deploys correctly on my end.
